### ISSUE TITLE
Update colour options in picture_service.change_hair_colour

### ISSUE THREAD

**Issue by diego-cc** [HairdressingProject/styleme#18]
Currently, the available options to change hair colours in the [change_hair_colour](https://github.com/HairdressingProject/styleme/blob/master/Backend/PicturesAPI/app/services/picture_service.py#L232 "change hair colour function") function are:

```python
colours = {"green": [25, 250, 32], "yellow": [30, 252, 249], "orange": [30, 108, 252], "burgundy": [32, 0, 128],
                   "ruby": [95, 17, 224], "coral": [80, 127, 255], "violet": [211, 0, 148]}
```

The colours above should be updated to the ones specified by clients, as shown [here](https://github.com/HairdressingProject/styleme/blob/master/Design/Style_Me/Mockups/Select_Hair_Colour_v2.pdf "Select Hair Colour UI")

**Comment by ggornes** [comment]
Commit `https://github.com/HairdressingProject/styleme/commit/f8291710d70a068507e6d6745a3f395c10f47561` fixes issue #18
